version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PREMIUM_ROLE_ID=${PREMIUM_ROLE_ID}
      - BOOSTER_ROLE_ID=${BOOSTER_ROLE_ID}
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
